### ISSUE TITLE
Unable to add fuel from other mods

### ISSUE THREAD

**Issue by Dokharus** [henkelmax/ultimate-car-mod#21]
**Please read the [FAQ](https://modrepo.de/minecraft/car/faq) before submitting a bug report!**

**Bug description**
When trying to put biodiesel from Immersive Engineering in a gas station, it just doesn't work (Of course after edition of .minecraft\saves\Test\serverconfig\car\fuel.toml

**Steps to reproduce the issue**
Add the new fuel to the config file
launch the game
try to put the newly added fuel to a gas station through either a pipe and a tank or a bucket

**Expected behavior**
The internal gas station tank fills up

**Log files**
[fuel.toml](https://gist.github.com/Dokharus/edc41440b79bf4d0a25ed789eb5157fe)
[debug.log](https://gist.github.com/Dokharus/91c0fbe8edf74980b621f8225cf92875)

**Versions**
Minecraft 1.16.4
Forge 35.1.4
car-1.16.4-1.0.5
(Using MultiMC version 0.6.11 - 1430)

**Other mods**
A lot, but tried without any (except for UCM and UPM) and did not work with minecraft:lava

**Screenshots (Optional)**
![2021-01-08_18 02 36](https://user-images.githubusercontent.com/66277770/104043483-30e68200-51dc-11eb-8f54-97ad0beff74d.png)

**Comment by henkelmax** [comment]
The config you edited is just for the cars.
To add a fluid to the gas station you have to add it to `machines.gas_station` in the car-server.toml

Example:

``` toml
	[machines.gas_station]
		#Range: 1 ~ 32767
		transfer_rate = 5
		#If it starts with '#' it is a tag
		valid_fuels = ["#car:gas_station", "minecraft:lava"]
```
